import { StyleSheet } from "react-native";

export default StyleSheet.create({
  //HOME
  Home: {
    justifyContent: "space-evenly",
    maxHeight: "100%",

    backgroundColor: "#f0f0f0",
  },

  textStyle: { color: "#FFFFFF", textAlign: "center", fontSize: 16 },
  container: {
    flex: 1,
  },

  content: {
    gap: 20,
    backgroundColor: "#f0f0f0",
  },
  contenthome: {
    flexGrow: 1,
    height: "33%",
    gap: 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "blue",
  },
  texto: {
    color: "#26A20A",
    textAlign: "center",
    fontFamily: "Lato_400Regular",
  },
  btntexto: {
    color: "#26A20A",
    textAlign: "center",
    fontFamily: "Lato_400Regular",
    fontSize: 17,
  },
  botao: {
    alignContent: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 4.65,
    elevation: 8,
    backgroundColor: "#ffffff",
  },
  btncadastrar: {
    flexDirection: "row",
    alignItems: "center",
    width: "87%",
    height: "70%",
    backgroundColor: "#fff",
    gap: 20,
    borderRadius: 10,
  },
  cadastros: {
    borderRadius: 10,
    width: "42%",
    height: "80%",
  },
  msg: {
    borderRadius: 15,
    marginVertical: 50,
    color: "#26A20A",
    fontFamily: "Lato_400Regular",
    fontSize: 20,
    padding: 15,
    textAlign: "justify",
  },
  //LISTAR CRIANCA
  Lista: {
    borderWidth: 0.5,
    borderColor: "#26A20A",
    justifyContent: "center",
    alignContent: "center",
    backgroundColor: "#ffffff",
    width: "95%",
    marginBottom: 15,
    marginHorizontal: "2%",
    borderRadius: 5,
  },
  nomeLista: { fontWeight: "bold", fontSize: 16 },
  textoLista: { fontSize: 15, lineHeight: 22 },
  apagar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },

  // CADASTRO
  viewinput: {
    padding: 7,
    height: "100%",
    justifyContent: "space-between",
    flex: 1,
  },
  input: {
    width: "100%",
    borderWidth: 0.7,
    marginTop: 15,
    padding: 10,
    borderRadius: 25,
    borderColor: "#26A20A",
  },
  btnretangular: {
    borderRadius: 10,
    width: "90%",
    height: 65,
    backgroundColor: "#26A20A",
    justifyContent: "center",
    marginHorizontal: "5%",
  },
  viewbtn: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginVertical: 50,
  },
  btnav: {
    justifyContent: "center",
    width: 80,
    height: 80,
  },
  cadtexto: {
    textAlign: "center",
    marginTop: 10,
    fontSize: 15,
    fontWeight: "600",
  },
  //erros
  error: {
    marginStart: 10,
    marginBottom: 5,
    marginTop: 3,
    color: "red",
  },
  //DetalhesCriancas
  detalhes: {
    flex: 1,
    justifyContent: "space-between",
  },
  dtlsviewbtn: { flexDirection: "row", marginTop: 15 },
  vieweditarinput: {
    borderColor: "#26A20A",
    borderWidth: 1,
    borderRadius: 25,
    padding: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  confirmar: { flexDirection: "row", gap: 10 },
  editarinput: { width: "80%" },
  btnsdetalhes: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginBottom: 50,
  },
  btndetalhes: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#26A20A",
    borderRadius: 50,
    width: 80,
    height: 80,
    // marginBottom: 50,
  },
  btnsave: {
    alignItems: "flex-end",
    marginBottom: "10%",
    flex: 1,
    justifyContent: "flex-end",
  },
  dtlhsText: { color: "#FFF" },
  textbtn: {
    color: "#FFFFFF",
    fontSize: 25,
    textAlign: "center",
  },
  // VACINAS
  idadevcn: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 20,
    textAlign: "center",
  },
  titlevcn: {
    textAlign: "center",
    fontWeight: "bold",
    padding: 3,
    backgroundColor: "#00008b",
    color: "#FFF",
    fontSize: 16,
  },
  tabvcn: {
    justifyContent: "center",
    alignContent: "center",
    backgroundColor: "#ffffff",
    width: "80%",
    marginTop: 15,
    marginHorizontal: "10%",
    borderRadius: 5,
  },
  descvcn: { fontSize: 16 },
  btnaddvacina: {
    marginTop: 30,
    backgroundColor: "#26A20A",
    padding: 12,
    justifyContent: "center",
    width: "80%",
    marginHorizontal: "10%",
    borderRadius: 10,
  },
  addInput: { borderBottomWidth: 0.5, height: 35 },
  // pesos
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 20, marginLeft: 20 },
  pesoItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderColor: "#DDD",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: 20,
  },
  pesoText: { fontSize: 16 },
  pesoTexto: {
    fontSize: 16,
    color: "gray",
    textAlign: "center",
    marginTop: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    width: "82%",
    padding: 20,
    backgroundColor: "#FFF",
    borderRadius: 10,
    alignItems: "center",
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", marginBottom: 15 },

  //modal
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    justifyContent: "space-between",
    width: "90%",
    height: "22%",
    margin: 20,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  btnview: {
    flexDirection: "row",
    gap: 15,
  },
  button: {
    flex: 1,
    borderRadius: 20,
    padding: 9,
    elevation: 2,
    backgroundColor: "#26A20A",
  },
  buttonPeso: {
    borderRadius: 20,
    padding: 9,
    elevation: 2,
    backgroundColor: "#26A20A",
  },
  pesoModal: {
    flexDirection: "row",
    flexGrow: 1,
    marginTop: 15,
    gap: 10,
  },

  modalText: {
    fontSize: 17,
  },

  containersobre: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    padding: 20,
  },
  cardsobre: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    maxWidth: 600,
    width: "100%",
  },
  titlesobre: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  paragrafosobre: {
    fontSize: 16,
    marginBottom: 10,
    textAlign: "justify",
  },
  destaquesobre: {
    color: "#26A20A",
    fontWeight: "bold",
  },
});
